<?php
use Drupal\am_registration\Controller\DeleteLinkController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Access\AccessResult;
// BSD controllor
use \Drupal\am_bsd_tools\Controller\amBSDToolsController;

/**
 * Implements hook_page_attachments().
 */
function am_registration_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'am_registration/am_create_account';
}

/**
* Implements hook_mail().
*/
function am_registration_mail($key, &$message, $params) {

 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'send_login_link':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = $params['subject'];
     $message['body'][] = $params['body'];
     // $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
     $message['headers'] = array(
        'MIME-Version' => '1.0',
        'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
        'Content-Transfer-Encoding' => '8Bit',
        'X-Mailer' => 'Drupal'
      );
     break;
 }
}

/**
 * Implements hook_user_logout().
 */
function am_registration_user_logout($account) {

	if(isset($_SERVER['PANTHEON_ENVIRONMENT'])) {
		if($_SERVER['PANTHEON_ENVIRONMENT'] == 'live') {
			createCookie('authcookie', '', -1, '/', '.americamagazine.org');
   		createCookie('partialauthcookie', '', -1, '/' ,'.americamagazine.org');
		}
		elseif ($_SERVER['PANTHEON_ENVIRONMENT'] == 'test') {
			createCookie('authcookie','',-1,'/','.test-americad8.pantheonsite.io');
   		createCookie('partialauthcookie','',-1,'/','.test-americad8.pantheonsite.io');
		}
		else {
		 createCookie('authcookie','',-1,'/','.dev-americad8.pantheonsite.io');
		 createCookie('partialauthcookie','',-1,'/','.dev-americad8.pantheonsite.io');
		}
	}
}

/**
 * Helper function to remove cookie.
 */
function createCookie($name, $value='', $maxage=0, $path='', $domain='', $secure=false, $HTTPOnly=false) { 
    $ob = ini_get('output_buffering'); 

    // Abort the method if headers have already been sent, except when output buffering has been enabled 
    if ( headers_sent() && (bool) $ob === false || strtolower($ob) == 'off' ) 
        return false; 

    if ( !empty($domain) ) { 
        // Fix the domain to accept domains with and without 'www.'. 
        if ( strtolower( substr($domain, 0, 4) ) == 'www.' ) $domain = substr($domain, 4); 
        // Add the dot prefix to ensure compatibility with subdomains 
        if ( substr($domain, 0, 1) != '.' ) $domain = '.'.$domain; 

        // Remove port information. 
        $port = strpos($domain, ':'); 

        if ( $port !== false ) $domain = substr($domain, 0, $port); 
    } 

    // Prevent "headers already sent" error with utf8 support (BOM) 
    //if ( utf8_support ) header('Content-Type: text/html; charset=utf-8'); 
    header('Set-Cookie: '.rawurlencode($name).'='.rawurlencode($value) 
                                .(empty($domain) ? '' : '; Domain='.$domain) 
                                .(empty($maxage) ? '' : '; Max-Age='.$maxage) 
                                .(empty($path) ? '' : '; Path='.$path) 
                                .(!$secure ? '' : '; Secure') 
                                .(!$HTTPOnly ? '' : '; HttpOnly'), false); 
    return true; 
} 




/**
 * Implements hook_user_cancel().
 */
function am_registration_user_delete($account) {

	try{
		 // Delete any previous link
         $delete_result = new DeleteLinkController;
         $value = $delete_result->delete($account->id());
       }catch (Exception $e) {
        drupal_set_message("Some error occured","error");
      return new RedirectResponse('/user/login');
    }
	
}


//If content tpye is Book OR Sponsorship then access denied showing
function am_registration_node_access($node, $op, $account) {
  if ($op == 'view') {
    if($node->bundle() == "book" || $node->bundle() == "sponsorship"){
      return AccessResult::forbidden();
    }
  }
}

/**
 * Return information about forms that can be protected by Mollom.
 *
 * Mollom invokes this hook for all modules to gather information about forms
 * that can be protected. Only forms that have been registered via this hook are
 * configurable in Mollom's administration interface.
 *
 * @return
 *   An associative array containing information about the forms that can be
 *   protected, keyed by $form_id:
 *   - title: The human-readable name of the form.
 *   - entity: (optional) The internal name of the entity type the form is for,
 *     e.g. 'node' or 'comment'. This is required for all forms that will store
 *     the submitted content persistently. It is only optional for forms that do
 *     not permanently store the submitted form values, such as contact forms
 *     that only send an e-mail, but do not store it in the database.
 *     Note that forms that specify 'entity' also need to specify 'post_id' in
 *     the 'mapping' (see below).
 *   - delete form: (optional) The $form_id of a delete confirmation form
 *     constructor function for 'entity'. Mollom automatically adds the
 *     "Report as inappropriate" options to this confirmation form. Requires a
 *     'post_id' mapping via hook_mollom_form_info(). Requires the delete
 *     confirmation form constructor to assign the mapped post_id key in $form
 *     as a #value. See http://drupal.org/node/645374 for examples. Optionally
 *     limit access to report options by defining 'report access' permissions.
 *   - delete submit: (optional) The submit element for button-level submit
 *     handlers.  This defines the element where the delete submit handlers
 *     are attached.  If the element is nested it should be indicated like
 *     "parent[child][submit" similar to FormState->setErrorByName.  If not
 *     indicated, then form-level submit handlers will be used.
 *   - report path: (optional) A Drupal system path pattern to be used for
 *     reporting an entity to Mollom via a "Report to Mollom" link in e-mail
 *     notifications. This typically points to the menu router path that allows
 *     to delete an entity. The placeholder '%id' is dynamically replaced with
 *     the entity ID. For example, user_mollom_form_list() specifies
 *     'user/%id/cancel'.
 *   - report access: (optional) A list containing user permission strings, from
 *     which the current user needs to have at least one. Should only be used if
 *     no "report access callback" was defined.
 *   - report access callback: (optional) A function name to invoke to check
 *     access to Mollom's dedicated "report to Mollom" form, which should return
 *     either TRUE or FALSE (similar to menu access callbacks).
 *   - report delete callback: (optional) A function name to invoke to delete an
 *     entity after reporting it to Mollom.  The callback will receive the
 *     entity id as an argument.
 *   - entity report access callback: (optional) A function name to invoke to
 *     determine if a user has access to report the entity that the form is for.
 *
 * @see hook_mollom_form_info()
 */
function am_registration_mollom_form_list() {
  // One time login form.
  $forms['registration_form'] = array(
    'title' => t('One time login form'),
  );
  
  return $forms;
}

/**
 * Return information about a form that can be protected by Mollom.
 *
 * @param $form_id
 *   The form id to return information for.
 *
 * @return
 *   An associative array describing the form identified by $form_id:
 *   - mode: (optional) The default protection mode for the form, which can be
 *     one of:
 *     - MOLLOM_MODE_ANALYSIS: Text analysis of submitted form values with
 *       fallback to CAPTCHA.
 *     - MOLLOM_MODE_CAPTCHA: CAPTCHA-only protection.
 *   - type: Internal use only.
 *   - bypass access: (optional) A list of user permissions to check for the
 *     current user to determine whether to protect the form with Mollom or do
 *     not validate submitted form values. If the current user has at least one
 *     of the listed permissions, the form will not be protected.
 *   - moderation callback: (optional) A function name to invoke when a form
 *     submission would normally be discarded. This allows modules to put such
 *     posts into a moderation queue (i.e., to accept but not publish them) by
 *     altering the $form or $form_state that are passed by reference.
 *   - context created callback: (optional) A function to invoke to determine
 *     the creation of the context for this form for textual analysis.  The
 *     function receives the id of the entity being processed and should
 *     return the UNIX timestamp for the creation date or FALSE if unavailable.
 *   - elements: (optional) An associative array of elements in the form that
 *     can be configured for Mollom's text analysis. The site administrator can
 *     only select the form elements to process (and exclude certain elements)
 *     when a form registers elements. Each key is a form API element #parents
 *     string representation of the location of an element in the form. For
 *     example, a key of "myelement" denotes a form element value on the
 *     top-level of submitted form values. For nested elements, a key of
 *     "parent][child" denotes that the value of 'child' is found below 'parent'
 *     in the submitted form values. Each value contains the form element label.
 *     If omitted, Mollom can only provide a CAPTCHA protection for the form.
 *   - mapping: (optional) An associative array to explicitly map form elements
 *     (that have been specified in 'elements') to the data structure that is
 *     sent to Mollom for validation. The submitted form values of all mapped
 *     elements are not used for the post's body, so Mollom can validate certain
 *     values individually (such as the author's e-mail address). None of the
 *     mappings are required, but most implementations most likely want to at
 *     least denote the form element that contains the title of a post.
 *     The following mappings are possible:
 *     - post_id: The form element value that denotes the ID of the content
 *       stored in the database.
 *     - post_title: The form element value that should be used as title.
 *     - post_body: Mollom automatically assigns this property based on all
 *       elements that have been selected for textual analysis in Mollom's
 *       administrative form configuration.
 *     - author_name: The form element value that should be used as author name.
 *     - author_mail: The form element value that should be used as the author's
 *       e-mail address.
 *     - author_url: The form element value that should be used as the author's
 *       homepage.
 *     - author_id: The form element value that should be used as the author's
 *       user uid.
 *     - author_openid: The form element value that consists of Open IDs
 *       of the content author, separated by whitespace.
 *     - author_ip: Mollom automatically assigns the user's IP address if no
 *       explicit form element value mapping was specified.
 */
function am_registration_mollom_form_info($form_id) {
  switch ($form_id) {
    // Mymodule's comment form.
    // case 'mymodule_comment_form':
    //   $form_info = array(
    //     'mode' => MOLLOM_MODE_ANALYSIS,
    //     'bypass access' => array('administer comments'),
    //     'mail ids' => array('mymodule_comment_mail'),
    //     'elements' => array(
    //       'subject' => t('Subject'),
    //       'body' => t('Body'),
    //     ),
    //     'mapping' => array(
    //       'post_id' => 'cid',
    //       'post_title' => 'subject',
    //       'author_name' => 'name',
    //       'author_mail' => 'mail',
    //       'author_url' => 'homepage',
    //     ),
    //   );
    //   return $form_info;

    // Mymodule's user registration form.
    case 'registration_form':
      $form_info = array(
        'mode' => MOLLOM_MODE_CAPTCHA,
      );
      return $form_info;
  }
}



/**
 * Implementation of hook_form_alter()
 */
function am_registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  global $base_url;

  if ($form_id == 'social_login_block_form') {

  // echo '<pre>';var_dump($form);die();
  //   $form['#prefix'] = '<div id="loginModel">';
  //   $form['#suffix'] = '</div>';
   
  //   $form['#title'] = t('Log in to your account');
  //   $form['name']['#title_display'] = 'invisible';
  // $form['mail'] = array(        
  //       '#markup' => t('<div class="amlogintitle">Enter your email address and password</div>'),
  //       '#weight' => -99,        
  //     );  
  // $form['pass']['#title_display'] = 'invisible';  
  // $form['name']['#attributes'] = array('placeholder' => t('Email address'),'class' => array('form-control'));
  // $form['pass']['#attributes'] = array('placeholder' => t('password'),'class' => array('form-control'));  
  //   $form['actions']['submit']['#prefix'] = '<div id="am_login_submit">';
  // $form['actions']['submit']['#suffix'] = '</div>'; 
  //   $items = array();        
  //   $form['user_links'] = array(      
  //     '#markup' => t('<div class="loginLink"><a href="#">Send me a log in link</a></div><div class="forgotPasswordLink"><a href="#">Forgot my password</a></div>'),
  //     '#weight' => 100,
  //   );
  
 }

}