// #if false
//
// This is the header used in the production apps script code.
//
// #endif
/**
 * @file DrupalPublish.gs
 * @version // #put VERSION+"\n *"
 * Released: // #put RELEASE_DATE() +"\n *"
// #ifdef DEBUG
 * Debug logging: ON
// #else
 * Debug logging: OFF
// #endif
 *
 * ******************************************************************
 * **************** DO NOT EDIT THIS FILE DIRECTLY ******************
 * ******************************************************************
 * **                                                              **
 * ** The code for this add-on is maintained along with the module **
 * ** code. Changes to this code will be overwritten on the next   **
 * ** update. See the README for instructions on compiling.        **
 * ******************************************************************
 *
 * @copyright 2016 Harmonica, LLC
 * @author Ken Ficara <ken@harmoni.ca>
 *
 * DrupalPublish is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
